version: '3.8'

services:
  gal_db:
    image: postgres:15
    container_name: galicia_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: galicia_api
    ports:
      - "8000:8000"
    depends_on:
      gal_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_HOST: gal_db
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./alembic:/app/alembic
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: