"""Add new Airline fields

Revision ID: 198b6cb58952
Revises: 5e68cbac0c86
Create Date: 2025-09-30 16:13:00.481715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198b6cb58952'
down_revision: Union[str, Sequence[str], None] = '5e68cbac0c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airlines', sa.Column('alias', sa.String(length=255), nullable=True))
    op.add_column('airlines', sa.Column('icao_code', sa.String(length=10), nullable=True))
    op.add_column('airlines', sa.Column('callsign', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_airlines_icao_code'), 'airlines', ['icao_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airlines_icao_code'), table_name='airlines')
    op.drop_column('airlines', 'callsign')
    op.drop_column('airlines', 'icao_code')
    op.drop_column('airlines', 'alias')
    # ### end Alembic commands ###
