"""Initial migration

Revision ID: 233e5e311209
Revises: 
Create Date: 2025-09-25 17:03:26.796227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233e5e311209'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('iata_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airlines_country'), 'airlines', ['country'], unique=False)
    op.create_index(op.f('ix_airlines_iata_code'), 'airlines', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airlines_id'), 'airlines', ['id'], unique=False)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_altitude'), 'airports', ['altitude'], unique=False)
    op.create_index(op.f('ix_airports_code'), 'airports', ['code'], unique=True)
    op.create_index(op.f('ix_airports_country'), 'airports', ['country'], unique=False)
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_code', sa.String(length=10), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('origin_code', sa.String(length=10), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_code', sa.String(length=10), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_airline_date', 'routes', ['airline_id', 'flight_date'], unique=False)
    op.create_index('idx_route_origin_dest', 'routes', ['origin_id', 'destination_id'], unique=False)
    op.create_index(op.f('ix_routes_airline_code'), 'routes', ['airline_code'], unique=False)
    op.create_index(op.f('ix_routes_airline_id'), 'routes', ['airline_id'], unique=False)
    op.create_index(op.f('ix_routes_destination_code'), 'routes', ['destination_code'], unique=False)
    op.create_index(op.f('ix_routes_flight_date'), 'routes', ['flight_date'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_origin_code'), 'routes', ['origin_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_origin_code'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_flight_date'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_code'), table_name='routes')
    op.drop_index(op.f('ix_routes_airline_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_airline_code'), table_name='routes')
    op.drop_index('idx_route_origin_dest', table_name='routes')
    op.drop_index('idx_route_airline_date', table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_country'), table_name='airports')
    op.drop_index(op.f('ix_airports_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_altitude'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_id'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_iata_code'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_country'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
