"""Add AuditLog

Revision ID: 5e68cbac0c86
Revises: d086f592d869
Create Date: 2025-09-29 20:26:06.235931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e68cbac0c86'
down_revision: Union[str, Sequence[str], None] = 'd086f592d869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_index(op.f('ix_audits_method'), 'audits', ['method'], unique=False)
    op.create_index(op.f('ix_audits_path'), 'audits', ['path'], unique=False)
    op.create_index(op.f('ix_audits_status_code'), 'audits', ['status_code'], unique=False)
    op.create_index(op.f('ix_audits_timestamp'), 'audits', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audits_timestamp'), table_name='audits')
    op.drop_index(op.f('ix_audits_status_code'), table_name='audits')
    op.drop_index(op.f('ix_audits_path'), table_name='audits')
    op.drop_index(op.f('ix_audits_method'), table_name='audits')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_table('audits')
    # ### end Alembic commands ###
