"""Add support for IATA and ICAO codes for airports

Revision ID: 698048f97502
Revises: ff76945348d3
Create Date: 2025-09-27 02:25:33.191827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698048f97502'
down_revision: Union[str, Sequence[str], None] = 'ff76945348d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports', sa.Column('iata_code', sa.String(length=10), nullable=True))
    op.add_column('airports', sa.Column('icao_code', sa.String(length=10), nullable=True))
    op.add_column('airports', sa.Column('utc_offset', sa.Float(), nullable=True))
    op.add_column('airports', sa.Column('continent_code', sa.String(length=10), nullable=True))
    op.add_column('airports', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_airports_code'), table_name='airports')
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airports_icao_code'), 'airports', ['icao_code'], unique=True)
    op.drop_column('airports', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_airports_icao_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.create_index(op.f('ix_airports_code'), 'airports', ['code'], unique=True)
    op.drop_column('airports', 'timezone')
    op.drop_column('airports', 'continent_code')
    op.drop_column('airports', 'utc_offset')
    op.drop_column('airports', 'icao_code')
    op.drop_column('airports', 'iata_code')
    # ### end Alembic commands ###
